apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spark
spec:
  tolerations:
  - key: <name>.com/worker-group
    operator: Equal
    value: default-spot-arm
    effect: NoSchedule
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: <name>.com/worker-group
            operator: In
            values: ["default-spot-arm"]