apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkConnect
metadata:
  name: spark-connect
  namespace: default
  labels:
    app: spark-connect
spec:
  sparkVersion: 3.5.3
  server:
    template:
      metadata:
        labels:
          key1: value1
          key2: value2
        annotations:
          key3: value3
          key4: value4
      spec:
        tolerations:
        - key: <name>.com/worker-group
          operator: Equal
          value: default-spot-arm
        containers:
        - name: spark-kubernetes-driver
          image: spark:4.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
              
        serviceAccount: spark-operator-spark
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 0
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
        
  executor:
    instances: 2
    cores: 1
    memory: 512m
    template:
      metadata:
        labels:
          key1: value1
          key2: value2
        annotations:
          key3: value3
          key4: value4
      spec:
        tolerations:
        - key: <name>/worker-group
          operator: Equal
          value: default-spot-arm
        containers:
        - name: spark-kubernetes-executor
          image: spark:4.0.0
          imagePullPolicy: Always
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 0
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
  sparkConf:
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://<bucket>/"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    #spark.eventLog.dir: "file:///tmp"
    spark.driver.extraJavaOptions: "-Duser.home=/tmp"
    spark.executor.extraJavaOptions: "-Duser.home=/tmp"
    spark.jars.packages: "org.apache.hadoop:hadoop-aws:3.4.0,com.amazonaws:aws-java-sdk-bundle:1.12.262"

    # spark.jars.packages: "org.apache.spark:spark-connect_2.12:3.5.3"
    # spark.hadoop.fs.s3a.aws.credentials.provider: "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
   
    
